"""init

Revision ID: 86428e1abada
Revises: 
Create Date: 2022-11-11 16:12:09.824260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86428e1abada'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('ssh_key', sa.String(length=255), nullable=True),
    sa.Column('alias', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_alias'), 'device', ['alias'], unique=True)
    op.create_index(op.f('ix_device_id'), 'device', ['id'], unique=False)
    op.create_index(op.f('ix_device_name'), 'device', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_name'), table_name='device')
    op.drop_index(op.f('ix_device_id'), table_name='device')
    op.drop_index(op.f('ix_device_alias'), table_name='device')
    op.drop_table('device')
    # ### end Alembic commands ###
