format:
	# pipenv run autoflake --remove-all-unused-imports --recursive --remove-unused-variables --in-place project --exclude=__init__.py
	pipenv run isort --profile black project
	pipenv run black project